# Generated by Django 3.2.9 on 2021-11-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barba', '0004_auto_20211118_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
