# Generated by Django 3.2.9 on 2021-11-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barba', '0006_auto_20211119_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
