# Generated by Django 3.2.9 on 2021-11-21 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barba', '0007_alter_venta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio',
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barba.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartidor', to='barba.empleado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barba.empleado'),
        ),
    ]
